import { useMemo } from "react";

const themes = {
  "purple-blue": {
    name: "Purple Blue (Current)",
    light: {
      primary: "from-purple-600 to-blue-600",
      primarySolid: "bg-purple-600",
      secondary: "bg-blue-100",
      accent: "bg-purple-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-purple-500 to-blue-500",
      primarySolid: "bg-purple-500",
      secondary: "bg-blue-900/30",
      accent: "bg-purple-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "emerald-teal": {
    name: "Emerald Teal",
    light: {
      primary: "from-emerald-600 to-teal-600",
      primarySolid: "bg-emerald-600",
      secondary: "bg-teal-100",
      accent: "bg-emerald-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-emerald-500 to-teal-500",
      primarySolid: "bg-emerald-500",
      secondary: "bg-teal-900/30",
      accent: "bg-emerald-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "rose-orange": {
    name: "Rose Orange",
    light: {
      primary: "from-rose-500 to-orange-500",
      primarySolid: "bg-rose-500",
      secondary: "bg-orange-100",
      accent: "bg-rose-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-rose-400 to-orange-400",
      primarySolid: "bg-rose-400",
      secondary: "bg-orange-900/30",
      accent: "bg-rose-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "indigo-cyan": {
    name: "Indigo Cyan",
    light: {
      primary: "from-indigo-600 to-cyan-600",
      primarySolid: "bg-indigo-600",
      secondary: "bg-cyan-100",
      accent: "bg-indigo-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-indigo-500 to-cyan-500",
      primarySolid: "bg-indigo-500",
      secondary: "bg-cyan-900/30",
      accent: "bg-indigo-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "amber-red": {
    name: "Amber Red",
    light: {
      primary: "from-amber-500 to-red-500",
      primarySolid: "bg-amber-500",
      secondary: "bg-red-100",
      accent: "bg-amber-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-amber-400 to-red-400",
      primarySolid: "bg-amber-400",
      secondary: "bg-red-900/30",
      accent: "bg-amber-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "violet-pink": {
    name: "Violet Pink",
    light: {
      primary: "from-violet-600 to-pink-600",
      primarySolid: "bg-violet-600",
      secondary: "bg-pink-100",
      accent: "bg-violet-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-violet-500 to-pink-500",
      primarySolid: "bg-violet-500",
      secondary: "bg-pink-900/30",
      accent: "bg-violet-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "slate-blue": {
    name: "Slate Blue",
    light: {
      primary: "from-slate-600 to-blue-600",
      primarySolid: "bg-slate-600",
      secondary: "bg-blue-100",
      accent: "bg-slate-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-slate-500 to-blue-500",
      primarySolid: "bg-slate-500",
      secondary: "bg-blue-900/30",
      accent: "bg-slate-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
  "green-blue": {
    name: "Green Blue",
    light: {
      primary: "from-green-600 to-blue-600",
      primarySolid: "bg-green-600",
      secondary: "bg-blue-100",
      accent: "bg-green-100",
      background: "bg-gray-50",
      card: "bg-white",
      text: "text-gray-900",
      textSecondary: "text-gray-600",
      border: "border-gray-200",
    },
    dark: {
      primary: "from-green-500 to-blue-500",
      primarySolid: "bg-green-500",
      secondary: "bg-blue-900/30",
      accent: "bg-green-900/30",
      background: "bg-gray-900",
      card: "bg-gray-800",
      text: "text-white",
      textSecondary: "text-gray-300",
      border: "border-gray-700",
    },
  },
};

export function useTheme(themeName = "purple-blue", mode = "light") {
  return useMemo(() => {
    return themes[themeName]?.[mode] || themes;
  }, [themeName, mode]);
}
export default themes;